### ISSUE TITLE
Problems when loading ui3 in Homeseer HStouch

### ISSUE THREAD

**Issue by stk1987** [bp2008/ui3#10]
Hello after v45 i can not open ui3 using HStouch on my android phone but i can open it with chrome on the phone. when i try to open it in the HStouch app it hangs up loading H.264 player. If i replace ui3.js file with v45 it works fine. see below. if you have need any more info on this please let me know.

https://forums.homeseer.com/forum/3rd-party-plug-ins-scripts/plug-ins-by-author/click-here-for-list-of-author-forums/highpeak-plug-ins/blue-iris-plug-in/110093-hstouch-blueiris?p=1238434#post1238434

**Comment by bp2008** [comment]
Thanks for letting me know.  Sure enough, there is a script error occurring when local storage is not available, but apparently the Homeseer app won't show "alert dialogs" which is how UI3 tries to report script errors to you, so it was not obvious at all why loading was stalled :)

The next UI3 release should have this bug fixed.

**Comment by stk1987** [comment]
awesome thank you. I'll make this as fixed and when the new release comes out ill trying it out,

**Comment by bp2008** [comment]
This should be fixed in version 51 which is now available on the releases tab.  If you need install instructions, see the main readme here: https://github.com/bp2008/ui3

**Comment by stk1987** [comment]
I just tested it and that fixed it thank you

**Comment by bp2008** [comment]
Glad to hear it!
