### ISSUE TITLE
One of my cameras is going black only when viewing via browser full screen mode

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#100]
Hopefully the screenshot will make this clear but I've just upgraded BI to the current latest version on my BI server and when viewing the remote stream via UI3 it works fine when it initially loads. 

However as soon as I click the icon bottom right to make the browser go full screen, my top left image goes black.    If I enable the left side controls to appear whilst in browser full screen the feed returns and its fine.  So its only when full screen and the 9 feeds are using all the available space with no other interface elements visible.

![blackbox issue](https://user-images.githubusercontent.com/3810108/154700312-d334a0cd-84bd-49b6-8c54-b63aa6e833a4.jpg)

**Comment by arkid** [comment]
Further testing reveals that this seems to happen only in certain video modes.   I was on "JPEG HD" and that is where the problem seems to be.   Changing to other options seems to resolve the problem.   

Still, it is a problem if the preference is to use JPEG HD.

**Comment by bp2008** [comment]
Closing issue as it is inactive, and unrelated to UI3.
