### ISSUE TITLE
HTML5 issues on mac OS?

### ISSUE THREAD

**Issue by bp2008** [bp2008/ui3#105]
MacOS Monterey, Safari.  Issues have been reported with HTML5 player looping back and playing old video again, FPS showing 0, etc.

**Comment by bp2008** [comment]
If anyone else has a problem with HTML5 video in UI3 on Safari on MacOS Monterey, please let me know.

**Comment by bp2008** [comment]
Hi @leechr80.

I'm sorry you're having this problem.  I posted about it [on ipcamtalk here](https://ipcamtalk.com/threads/blue-iris-ui3.23528/page-194#post-756459).  The workaround for now is to go to Main Menu (upper right corner of UI3) -> UI Settings -> Video Player and change the H.264 player to something else.  The JavaScript player is likely the only other player available, and it is less efficient but it still works where HTML5 doesn't.  WebCodecs is supposedly supported since iOS 16.4 based on their release notes, but it probably only shows up as an option in UI3 if you use an HTTPS reverse proxy server to access UI3.

[UI3-232](https://github.com/bp2008/ui3/releases/tag/232) available in the latest Blue Iris makes it a whole lot easier to self-troubleshoot this issue, by having the error message provide a link to a small help dialog, and it makes it much easier to access UI settings while you're being spammed by error toasts.

All browsers on iOS typically behave exactly the same because Apple won't allow apps include their own browser engine and they are all internally forced to use Safari.

I wish I knew more but I don't own any modern Apple devices so I haven't even seen this issue in person yet.  I've done internet searches and looked at safari 16.4 release notes for more information, but I've found nothing except people reporting this issue in UI3.  This is not particularly surprising because UI3 does low latency video in a way that very few other web applications do, and UI3 also is much better at reporting script errors to the user than most other web applications (which sweep errors under the proverbial rug).

**Comment by leechr80** [comment]
Hi @bp2008 thanks for the response, no need to apologise and it's almost the last straw for me to start finally looking at an android tablet/phone instead, just hard though once you end up deep in an ecosystem it's hard to move away from. Love your work on the UI3 interface, particularly the "timeline" implementation that allows that easy scroll back through video stream. 

I'd been looking through the blueiris forums and couldn't see any mention of it which I thought was odd, didn't realize ipcamtalk is the place to discuss. 

In my rush to post last night I forgot to mention am running UI version 232, Blue Iris Release 5.7.4.2 x64

Unfortunately I can't get to the UI Settings to try change the video codec as once the page loads it's straight into Live View which launches into millions of those errors and the page is completely unresponsive. 

Are there any URL options (ie: ui3.htm?codec=blah) I can feed it to force the codec to something else before the video stream starts ? Or any way to change the default codec at the webserver level in a config file somewhere maybe?

**Comment by bp2008** [comment]
That is very curious.  UI3-232 should have a little link saying "Click for Help" at the bottom of the HTML5 video error toasts.  Additionally the toast messages should no longer overlap the top bar and they should not overlap dialog boxes either.  I do understand it could make the page unresponsive though.  I clearly need to work on better handling of massive numbers of errors.

**Comment by bp2008** [comment]
I've just released [UI3-233](https://github.com/bp2008/ui3/releases/tag/233) with revised "Automatic" H.264 player selection logic that will not choose the HTML5 player on iOS 16.4 or newer until iOS 17 comes out (then it would try the HTML5 player again and we'll see what happens at that time).

**Comment by bp2008** [comment]
As I've heard nothing about HTML5 issues on mac OS in over a year now, I'm closing this issue.
