### ISSUE TITLE
Issue with Audio on Timeline

### ISSUE THREAD

**Issue by TheMrDrProf** [bp2008/ui3#106]
Hi all. I am experiencing some issues with audio during timeline playback. When using timeline and viewing LIVE, audio works fine:
<img width="960" alt="Capture1" src="https://user-images.githubusercontent.com/25834380/163731406-26539023-a74a-472c-809b-8182357433a1.PNG">

However, when scrolling into the past, the audio icon gets a strike through and does not play audio:
<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/25834380/163731407-26f4240e-abfa-4b82-a758-2af077099957.PNG">

When viewing the properties, it shoes the recording has audio. Exporting clips or viewing in main BI program has audio.
<img width="266" alt="Capture3" src="https://user-images.githubusercontent.com/25834380/163731408-9a6ab873-f032-45f9-a7d8-656a382ca90e.PNG">

Viewing stats in the past footage shows no audio stream or bitrate.
<img width="252" alt="Capture4" src="https://user-images.githubusercontent.com/25834380/163731409-b738ec07-0560-4303-8c00-b35f1ab924cd.PNG">

However, viewing live on timeline shows an audio stream.
<img width="249" alt="Capture5" src="https://user-images.githubusercontent.com/25834380/163731410-31ef60b1-ea23-4167-820c-669bd34dc191.PNG">

Mousing over the striked out audio icon shows the following:
<img width="337" alt="Capture6" src="https://user-images.githubusercontent.com/25834380/163731411-8a5da404-00a9-4ce4-a26e-1185fe0ac6f1.png">

Going to about UI3 shows these versions: UI3 version 207, Blue Iris version: 5.5.6.13

It seems there are others experiencing the issue as well: https://www.reddit.com/r/BlueIris/comments/tqj2lu/the_timeline_in_ui3_is_hugely_appreciated/

Let me know if there is anything I can do to help! Thanks in advance!

**Comment by bp2008** [comment]
Yep report it to BI support.  BI has actually never supported audio on the timeline even in the local console.  Not enough people have asked for it.

**Comment by bp2008** [comment]
Interesting. All I know is I brought this up with Ken (BI developer) around the time I was finishing up the timeline release in UI3 and he said audio wasn't in the local console either so we'd just have to wait.

UI3 already requests audio with the stream, just like it would with any other group stream, and BI doesn't deliver the audio.

So I still advise that you tell BI support if you haven't already.

**Comment by TheMrDrProf** [comment]
Ah gotcha. Makes sense then. I'll go throw a note their way and see what happens. Thanks for the info and for UI3. I'm only a week and a half into BI, so still learning, but love it. And use exclusively UI3 on computer and phone. Fantastic piece of software.

**Comment by XtremeOwnageDotCom** [comment]
Just stumbled upon this thread after finally tracking down the no-audio issue only on the timeline. Tossed a separate email out to support linking back here.

**Comment by bp2008** [comment]
Audio works for single cameras during timeline playback since Blue Iris 5.6.3 - October 26, 2022.

Still waiting for audio in multi-camera timeline playback.

**Comment by XtremeOwnageDotCom** [comment]
Well- that is more information then I got back from Blue Iris's support... At least its a step in the correct direction.

![image](https://user-images.githubusercontent.com/5262735/200663692-bac57159-3cdd-4465-a85b-95f750d8c119.png)

**Comment by TheMrDrProf** [comment]
Closing this issue. Unsure when it was added, but timeline in UI3 now has audio for "in the past/recordings". Appears Blue Iris is now delivering the audio.

![Screenshot 2024-10-05 234613](https://github.com/user-attachments/assets/7b1c5dcc-5c28-4032-bef1-e555add69b8d)
