### ISSUE TITLE
Feature Request: Timeline icon - Human , Car alerts

### ISSUE THREAD

**Issue by yffud** [bp2008/ui3#111]
The blue iris desktop timeline view now includes the AI detected alert icons like Human or Car as the timeline alert icon.

<img width="246" alt="Screen Shot 2022-05-13 at 5 19 50 PM" src="https://user-images.githubusercontent.com/6361383/168403531-cd8b7284-a29d-4669-b8b6-91711b91b1d6.png">

This is very helpful for a quick visual scan on the timeline and to narrow in on any activity.

**Comment by bp2008** [comment]
Added in [UI3-214](https://github.com/bp2008/ui3/releases/tag/214).
