### ISSUE TITLE
No Auto Login?

### ISSUE THREAD

**Issue by beebenutz** [bp2008/ui3#113]
There is no longer an option to automatically login.
Please add this option back to the login page!

Thanks!

**Comment by bp2008** [comment]
Proof?

**Comment by beebenutz** [comment]
This is now my login page...

https://drive.google.com/file/d/1682PKRFbQNFstlWoryn42buF6y36agfO/view?usp=sharing

**Comment by bp2008** [comment]
That is the old login page that used to come with Blue Iris over 4 years ago.  What BI version are you running?

Something must have gone wrong when BI tried to extract UI3.  You could try:
1. Install the latest BI update (again?)
2. Manually install the appropriate UI3 release into Blue Iris following instructions [here](https://github.com/bp2008/ui3).

**Comment by beebenutz** [comment]
I just tried to update to 5.5.6.21 from the previous "highly stable" release. The login is still the "old" version. Is there a way to flush the old out?
I already attempted to manually install it. 
Weird thing is this install is fresh. I did use my config backup, if that somehow affects the ui3.

**Comment by bp2008** [comment]
Restoring a backup shouldn't have affected anything.

Did you by chance just update from a very old installation of BI from before UI3?  If so, it has been known to happen where the web server's root directory still points at the old installation's `www` folder.  Look in BI settings > Web server, and make sure the "Root:" directory path ends with "\Blue Iris 5\www".

**Comment by bp2008** [comment]
When UI3 is extracted, it **replaces** the login.htm page with the upgraded version.  I'm not sure if Blue Iris even includes the old version of the page anymore, but if it does, it is supposed to be immediately overwritten.

**Comment by bp2008** [comment]
Here's login.htm properties (note that I use a custom location for my BI installation. Most people have it in Program Files instead of being installed in the root of drive C).

![image](https://user-images.githubusercontent.com/5639911/170583825-6ad4dfc0-b742-4e3c-bdee-b2578362f43e.png)

If you find your login.htm file and it is the same as what I showed above, then your BI web server is loading the wrong login.htm file.

**Comment by beebenutz** [comment]
My Login.htm matched the above.
I manually installed the UI3 again. 
The Login.htm is now different.

After a restart of BI service, and a web refresh, the login page was still the old version on my android tablet.
If I log out manually, the Login page is the new style again, but if I re-open the browser, the login page is back to old style again. 
The same thing happens on my PC browsers, however, the login page is only the old style until I Manully log out, then the browser only shows the new login page. Second PC does same thing.
Where is this old login page comming from? 
I had the same issue on my old windows install that  the HD failed in. 
New HD with fresh windows and fresh BI.
Soon as I try UI3, it's the old version again.
I thought that the old login page was a new login page because I hadn't seen it before. 
Back then (maybe 6 months ago) I thought I had to go back to an older version of UI3 to get the Auto login back. 
I did manually install UI3-200, I think. 
Installing UI3-200 did change the login page back to the new version with auto login. 
It stayed this way until the new Windows and BI install on a new HD. 
Now the old login is back. 
I tried clearing all cache and rebooting all devices. Old login keep returning like a bad girlfriend.
Here is a video of the happenings:
https://drive.google.com/file/d/16X45DDF9sybfnu1rm6LZHSu7_EJB8Dqc/view?usp=sharing

**Comment by bp2008** [comment]
In a normal install, the old login page does not exist.  So for you to still be loading it, on multiple devices even, it has to be coming from somewhere unexpected.  Maybe from a cache somewhere, but normally web browsers don't cache the root page that is delivered first when you load a page.  It could also be loading from a different copy of Blue Iris that you haven't mentioned, if your web server root path is wrong or if the address that the browser is loading is wrong.

If you ever see the old login page again in a browser that shows the address bar, take note of exactly what the URL is. Then note any differences in the URL when you have loaded UI3 and then logged out manually and gotten the modern login page.

Your video shows you loading UI3 through a home screen shortcut.  Maybe that is bugged and inappropriately caching the login page on the android version you're running.  I suggest you delete that shortcut and open UI3 in Chrome and then save a new shortcut to your home screen.  It might clear that up on the Android devices anyway.

If you're using any kind of proxy server or reverse proxy server, it could possibly be caching files inappropriately.

**Comment by beebenutz** [comment]
I already tried to replace the shortcut. Same results. I'll check the addresses and keep looking.

**Comment by beebenutz** [comment]
/jpegpull.htm was the old login address on PC

**Comment by bp2008** [comment]
Is that what it actually showed in the address bar while the old login page was showing?  Your jpegpull.htm file may have been replaced by login.htm's contents somehow... ?

**Comment by beebenutz** [comment]
Yes. Android tab shows /xlogin.htm?page=%2Fui3.htm
Even if I manually enter UI3.htm

**Comment by bp2008** [comment]
Oh, now that is interesting.  Ken must have kept the old login page around as xlogin.htm.

I wonder what the heck kind of logic is sending you there instead of to the new login page???  Whatever it is, it is certainly out of my control.  So I suggest you send a support request to BI support and tell them that you keep getting sent to xlogin.htm instead of login.htm.  Make it clear that you haven't bookmarked xlogin.htm or else they will probably suspect that first.

**Comment by beebenutz** [comment]
Mkay. Thanks for your time! Much appreciated!
