### ISSUE TITLE
Request for readme info regarding ui3 releases and BI update frequencies

### ISSUE THREAD

**Issue by ahaverty** [bp2008/ui3#136]
I'm just wondering what the usual update frequency is for new ui3 releases becoming available within BlueIris' native updater?

For example, the latest release doesn't seem to be available in BI updates yet, so I presume there's some packaging that has to happen on BI's side. Does that happen often or should I go the manual ui3 update route?

Does manually updating ui3 files in www/ cause any issues down the line with the automatic updater?

Thanks!

**Comment by bp2008** [comment]
Every Blue Iris update bundles the latest UI3 version at the time of the release.  I'm not sure if this is automated on their end but it has been very reliable as far as I have seen.

Blue Iris updates are not released on a predictable interval, however they are quite frequent, usually just a few days apart or about 8-14 releases per month.  The ipcamtalk forum maintains a [Blue Iris update log](https://ipcamtalk.com/tools/blueirisupdates/) where you can see this in detail.

Updating UI3 files manually as described in the readme here on github is fine.  It will not cause issues.  Whenever a Blue Iris update gets installed, it literally just has one of the UI3 release zips bundled in and it gets extracted into the www folder during the install process, overwriting all files that already exist.

**Comment by bp2008** [comment]
I should note that I make no special effort to maintain backwards compatibility with older Blue Iris releases. So, e.g. if you installed a UI3 release from 2023 into Blue Iris from 2021, you would likely find broken things.
