### ISSUE TITLE
[bug] UI3 PWA on Android always rotates, ignoring the OS's rotation lock setting

### ISSUE THREAD

**Issue by lightmaster** [bp2008/ui3#144]
If you have UI3's PWA installed, and have Android's Auto Rotate toggled disabled (so the screen will not rotate), UI3's PWA will still rotate. This is caused by the manifest.json entry `"orientation": "any"`. If this entry is removed and the PWA is reinstalled (or wait sufficient time for Android to check if there's an update to the manifest.json), then the PWA will start obeying the Auto Rorate setting.

**Comment by lightmaster** [comment]
I submitted a PR to correct this.

**Comment by bp2008** [comment]
Bizarre!  How did you figure that out?  I can find no evidence anywhere else that "orientation": "any" would break the rotation lock.

**Comment by lightmaster** [comment]
> Bizarre! How did you figure that out? I can find no evidence anywhere else that "orientation": "any" would break the rotation lock.

https://stackoverflow.com/questions/73956593/pwa-ignores-os-orientation-lock-on-android

**Comment by lightmaster** [comment]
I didn't think it had worked at first, but then I tried uninstalling the PWA and reinstalling it to force it to grab the new manifest, and it worked. PWA will get a new manifest eventually, based on whatever it's cache timeout is.

orientation is used to force the PWA into a specific orientation, however somewhat bizarrely, `"any"` makes it ignore the OS's rotation setting and forces it to always go by the accelerometer values. From what I can find, any defined value will override the OS setting.

**Comment by bp2008** [comment]
Implemented in [UI3-245](https://github.com/bp2008/ui3/releases/tag/245).
