### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by orditeck** [bp2008/ui3#15]
Hi,

Is there a way to get the cameras on top of each others (vertical layout) instead of next to each others (horizontal layout)?

Awesome UI so far. Thanks.

**Comment by orditeck** [comment]
Also, is there a way to hide the left toolbar? Can't find to toggle to do it.

**Comment by orditeck** [comment]
Would be cool to hide the left toolbar but keep the server status as overlay. Maybe I'll PR that if you're interested and the feature isn't already there.

**Comment by bp2008** [comment]
Instructions for modifying the camera layout are in the help file: https://bp2008.github.io/ui3/ui3/help/help.html#cameralayout

To hide the left bar you must also hide the top bar.  The first hotkey listed in UI Settings does this.  You can also start the UI with left and top bars hidden using a URL parameter: https://bp2008.github.io/ui3/ui3/help/help.html#urlparameters

There currently is no feature for moving the server status panel into an overlay.  I am not inherently opposed to push requests, but I suspect you are underestimating the difficulty of implementing such a feature.  It wouldn't be trivial for me to implement well, and I'm already deeply familiar with all the inner workings of UI3.

**Comment by orditeck** [comment]
Thanks!
