### ISSUE TITLE
Local layout control

### ISSUE THREAD

**Issue by bradleonard** [bp2008/ui3#157]
It would be great if there were the ability to create layouts in UI3 that are independent of Blue Iris. The ability to both resize and arrange camera streams would be excellent.

**Comment by bradleonard** [comment]
I am on BI version 5.3.x contemplating an update to get the Dynamic Group layout feature you are talking about.  I don't see the issue with limiting features per browser that you mentioned last. That is something that I would be willing to live with.

My main issue is that under certain conditions the UI3 layout seems to stack cameras narrow and vertically which reduces image size and leaves large amounts of unused real estate. If it was possible for UI3 to re-flow the camera layout with respect to available space in the browser, I would be happy.

![365190709_10161663074513760_7448345236183142654_n](https://github.com/bp2008/ui3/assets/28974262/cf560f81-358c-4571-8154-e8c62bfcad23)

**Comment by bp2008** [comment]
In the older Blue Iris versions, you can only affect the group layout very clumsily by editing the group frame size in Blue Iris's local console, group settings panel.

If you update Blue Iris, you will get the dynamic group layout feature.  These screenshots demonstrate roughly how it works:

![image](https://github.com/bp2008/ui3/assets/5639911/32dbe8af-55ed-4248-b2dc-cfa28b96edd5)

![image](https://github.com/bp2008/ui3/assets/5639911/86570095-85ce-4922-b4f8-585ffbd29dfe)

![image](https://github.com/bp2008/ui3/assets/5639911/254be6c2-1171-4260-b072-0bd879cddb85)

![image](https://github.com/bp2008/ui3/assets/5639911/586a796c-b4c8-40a1-8757-a798b46e2543)

You'll be able to right click the video in UI3 and choose Group Settings to get this dialog where you can change the resolution limit and lock in an aspect ratio if you like, as well as toggle camera names, borders, etc.

![image](https://github.com/bp2008/ui3/assets/5639911/2e954117-8348-41fc-9373-9a6de765c361)

![image](https://github.com/bp2008/ui3/assets/5639911/b2a2d5ed-6771-4d7e-ab21-2648193bfccb)

**Comment by bp2008** [comment]
Also as noted earlier, in newer Blue Iris you have much more power to customize group layouts via the new "Edit Layout" mode in the top bar of Blue Iris's local console.  See the icon with a pencil in it here in the top bar:

![image](https://github.com/bp2008/ui3/assets/5639911/c0f73de6-861b-4be9-af84-8e941f6f9f5a)

Most of the group layout controls are only in the local console (not in UI3 or mobile apps) but the modified layout does work in UI3 and the mobile apps.
