### ISSUE TITLE
iFrame on Site

### ISSUE THREAD

**Issue by schorges** [bp2008/ui3#159]
i'd like to show the great UI3 in my jarvis VIS for iobroker,
but it fails: 
`Refused chrome-error://chromewebdata/ to display frame because it set 'X-Frame-Options' to 'sameorigin'.`

<add name="X-Frame-Options" >

or is there a flag for input as iFrame like http://kolomonainioCam:81/ui3.htm&embedded=true

**Comment by bp2008** [comment]
UI3 can't control HTTP headers sent by Blue Iris's web server.
You're probably looking for this in Blue Iris Settings > Web server > Advanced:
![image](https://github.com/bp2008/ui3/assets/5639911/f4424602-9dbb-40b6-8105-27fa32af7504)

**Comment by schorges** [comment]
ok, thanks but now i have a new fail:

![image](https://github.com/bp2008/ui3/assets/18350246/613d5e59-ba2e-4920-895a-9f712d24b1e3)

**Comment by bp2008** [comment]
That typically happens when Blue Iris redirects to the login page instead of delivering the file that was requested.  And that happens because HTTP cookies are not working in your iframe.  I do not know what you'll need to do to fix that.

**Comment by schorges** [comment]
shit, now i use the HLS Stream `http://myservername:81/livestream.htm?cam=Index` 
it works, but without the alerts na dptz, but i works ...
