### ISSUE TITLE
Adressbar is visible on smartphone webapp

### ISSUE THREAD

**Issue by io43** [bp2008/ui3#165]
On android 14 + chrome 121 + UI3-268 when you add it as shortcut on home-screen the address bar is still visible, i tried to find the issue but the code seems to be there but isn't working

`<meta name="mobile-web-app-capable" content="yes">`
 in  ui3.html

and 

`"display": "standalone",`
in applet\manifest.json, 

any idea how to show the app in fullscreen like usual webapps?

i tried to change to 
`"display": "fullscreen",`
but it dont help at all

**Comment by io43** [comment]
well i just added local address to chrome://flags/#unsafely-treat-insecure-origin-as-secure i found out it here https://github.com/bp2008/ui3/issues/161

**Comment by bp2008** [comment]
That is weird, a secure context has never been a requirement for the address bar to disappear on Android when using a shortcut created via the browser's menu "Add to Home Screen" option.  I've been doing that for years.  Are you sure you were opening UI3 from the shortcut on the home screen?  I'd have tried closing all apps on the android device and then opening it fresh just to make sure no weirdness was happening.

**Comment by io43** [comment]
yea i tried all of that multiples times but well i use vanadium an chromium fork which have some hardening patchs that may interfer like this one https://github.com/GrapheneOS/Vanadium/blob/main/patches/0048-mark-non-secure-origins-as-dangerous.patch but i don't know, it is working fine anyways now with the flag

**Comment by bp2008** [comment]
Yeah it is probably a "security feature" of that browser.
