### ISSUE TITLE
Add transitions to "all groups" cycle changes

### ISSUE THREAD

**Issue by gaussey** [bp2008/ui3#167]
Just a basic dissolve/fade would be enough. I realise this is a fairly trivial request, even if not trivial to implement.

**Comment by bp2008** [comment]
Hello!

You'd need to ask Blue Iris Support for such a feature.  UI3 would have no reasonable way to implement such a transition since UI3 doesn't even know when the cycle changes.  It is just a single continuous video stream provided by Blue Iris.
