### ISSUE TITLE
h264 not working in chrome

### ISSUE THREAD

**Issue by 3ricj** [bp2008/ui3#17]
jpeg mode works great, but any of the h264 modes on chrome/windows does not operate correctly.   I have the latest version of chrome, blueiris version 4.8.3.0 x64/UI3 version 61.  

With h264 all I receive is a spinning arrow which never goes anywhere.  Jpeg works but is really low performance.  (5-6 fps)

**Comment by bp2008** [comment]
It is probably your antivirus / antimalware service on the PC that is running Chrome.  They have been known to intercept the stream, thinking it is a file download that needs to be scanned for viruses.

See if you can add an exception for the address you use to connect to Blue Iris.

**Comment by 3ricj** [comment]
The only anti-virus I use is windows defender, and it's disabled right now.

**Comment by bp2008** [comment]
Have a look in the Chrome developer tools (CTRL + SHIFT + I) and see if anything looks suspicious in the Console or Network tabs.

You should be able to see the H.264 streaming conneciton be made in the network tab, and see what is happening with it.

**Comment by 3ricj** [comment]
Ok, here's something.. best I can tell this url never responds:  

http://hostname:8100/video/Index/2.0?session=6a770d127f4b118717f017d0094652e0&audio=0&stream=0&h=294&kbps=256&extend=2

**Comment by bp2008** [comment]
That is the H.264 stream.

Got any antimalware stuff running on the BI server?  It is less likely but still possible for it to interfere there.

**Comment by 3ricj** [comment]
I had windows defender installed, but I just tried to disable the real time protection and it didn't have any change.   does BI log any web traffic?  I can't seem to find any http logs anywhere.

**Comment by bp2008** [comment]
I don't think it does.

**Comment by bp2008** [comment]
Try playing a clip, then seek to a few seconds before the end, and see if it begins playing at all after a few seconds have passed.

**Comment by 3ricj** [comment]
Nope.  Seeking to different positions doesn't let it play at all.   If we think it's intercepting the stream, then we should see the stream coming out of the BI server?  I can install wireshark and see if it's sending packets.

**Comment by bp2008** [comment]
Yeah, it should be coming out of the BI server unless some anti-spyware service on there is preventing it.

The reason for testing a clip near the end is that when a clip ends, Blue Iris will close the connection, and anything which has intercepted the stream should be able to do its scan, find that the payload is clean, and deliver it on to UI3.

**Comment by 3ricj** [comment]
Ok, you are right! I was able to make this work from a different system.   Let's close this bug -- I still don't know what is blocking me on my workstation, but it's specific to this machine.  A fresh windows 10 machine doesn't have problems.

**Comment by bp2008** [comment]
Ok.  Thanks for the update.
