### ISSUE TITLE
Unable to access UI3, "Your webserver session was lost"

### ISSUE THREAD

**Issue by lightmaster** [bp2008/ui3#173]
When I try to access my BI UI3 site, I get the below pop up and it fails to let me view my cameras and instead kicks me back to the login page. I have tried 4 different computers (3 running Windows and 1 running Pop_OS!) and 2 different users. And of those 4 computers, only 1 of them had ever accessed UI3 before. Also tried Firefox's Private Mode and Chrome's Incognito mode. I also tried on my Android phone and while it does work on the Chrome based PWA, it's not working on Firefox on Android either.

I have tried clearing all cookies in my browser, though since 3 of the computers have never gone to BI UI3 before, can't see how existing cookies could cause it.

![image](https://github.com/bp2008/ui3/assets/5307827/3c13e5a5-6eb1-415d-af20-7f8a17dece70)

**Comment by lightmaster** [comment]
Just tried reinstalling the previous version of BI (version 5.9.3.2) and I can access UI3 without any issues. If I install the current version (version 5.9.3.4), I get the above error again when trying to access UI3.

**Comment by bp2008** [comment]
Hmm.  I haven't seen that happen and I'm on 5.9.3.4.  If you can look at the ui3.htm page source, see what is in the `local_bi_session` variable around line 94.

**Comment by lightmaster** [comment]
I updated back to 5.9.3.4 for the third time to get that variable on that version, and of course it's working fine now. I'll keep trying it over the next day or 2 and see if it ever comes back.
