### ISSUE TITLE
Feature Request: Two Way Audio

### ISSUE THREAD

**Issue by editter** [bp2008/ui3#18]
Do you plan on allowing for two way audio between UI3 and a camera using a computer/phone microphone?  I assume the biggest limitation would be with the Blue Iris API but I haven't dug into that in a long time so maybe it has been updated to allow for that.

Thanks for the great work you have done with this!

**Comment by bp2008** [comment]
There's no plan for this.  The only way I'm aware of to get an audio stream out of the browser is to use WebRTC, which is a comically overcomplicated protocol that Blue Iris likely will never support.  It might be possible to do it with a web socket, but BI doesn't have a web socket server either.

**Comment by editter** [comment]
Thanks for the reply.  So even if there was a way to get a normal audio format does Blue Iris provide a way to pass that to the camera?

**Comment by bp2008** [comment]
Yeah, you can do it with the iOS or Android app I believe.  Never tried it myself.
