### ISSUE TITLE
Adjust padding for iOS "Add to Home Screen" icon

### ISSUE THREAD

**Issue by aesterling** [bp2008/ui3#183]
When using the "Add to Home Screen" feature in iOS to create a home screen icon for a PWA, the BI logo extends to the very edges of the squircle. This request is to increase the padding or decrease the logo size to match other apps and Apple's guidelines. Thank you in advance.

Screenshot comparing the native iOS BI app icon vs the UI3 PWA icon:

![home_screen_icon](https://github.com/user-attachments/assets/2aaed208-7c21-44b7-b871-23f0a2e74d5c)

**Comment by bp2008** [comment]
Lmao.  On Android it has white padding.  I don't suppose you know which graphic they are using?  There are a few different variants of this image if I recall.

**Comment by bp2008** [comment]
Marking each image that way is exactly how one would tell.  Blue Iris's web server has no cache that would be affected by rebooting the PC, so you can skip doing that.

The graphics used for this are in the `www/applet` folder actually, not in `www/ui3` (I should probably remove the files that are no longer used so they don't clutter new installs...).  Note there are `.webp` files in there which are a more modern image format more efficient than png but less widely supported.

`applet/launcher-icon.png` is the most likely candidate I think since it is referenced by the `<link rel="apple-touch-icon" id="ui3launcher2">` tag near the top of ui3.htm (the path for this is set further down the page via `document.getElementById("ui3launcher2").href = 'applet/launcher-icon.png?v=' + combined_version;`).

However if it isn't that one, then it could be any of the files in the `applet/logos` subdirectory.  I believe Android uses the `applet/logos/launcher-icon512_maskable.webp` file, so it is possible, although unlikely, that iOS is using the same one and just sizing it differently.

**Comment by aesterling** [comment]
Thanks! `applet/launcher-icon.png` is the image used for "Add to Home Screen" on my iPhone 15 Pro.

I scaled down the logo inside the 192x192 .png and replaced it in the applet folder, then re-added it to my iOS home screen. Now the logo size matches the native BI iOS icon, plus supports the new iOS 18 dark icons, unlike the native BI app.

Thanks for your help! Feel free to close this.

![app_icons](https://github.com/user-attachments/assets/5bbbd811-448e-4c3f-ab67-de3523343350)
![app_icons_dark](https://github.com/user-attachments/assets/8268d866-dbde-4a13-bafe-f429327ee85d)


Modified launcher-icon.png:
![launcher-icon](https://github.com/user-attachments/assets/bbf770b0-327f-44cf-b2e1-2b3da84b90aa)

**Comment by bp2008** [comment]
Why would replacing the graphic allow it to work as a dark mode icon?  The original graphic has a transparent background already, not white.  So I don't understand why that changed.

**Comment by bp2008** [comment]
Also, thanks for figuring that out.  I don't own a modern iOS device so must rely on others to test ;)

**Comment by aesterling** [comment]
Sorry, I was unclear. UI3 home screen icon has always worked in dark mode. I was comparing it to BI's iOS app, which doesn't currently support a dark mode icon.

**Comment by bp2008** [comment]
Aha!

**Comment by bp2008** [comment]
Would you try manually installing this by extracting into `www`, and see if the icon looks okay when UI3 is added to the home screen?

[UI3-272-pwa-test.zip](https://github.com/user-attachments/files/16460336/UI3-272-pwa-test.zip)

This one is coded to use `applet/logos/launcher-icon192_ios.webp` which is 9 KB versus 48 KB with your revision and it is scaled and centered a little bit differently.

**Comment by aesterling** [comment]
Here's a screenshot with the new logo on top. It appears to work fine and behaves correctly in dark mode. 

To me, it feels like this .webp logo is centered geometrically rather than optically and has too much white space on the left than the right. But people argue about that all the time. :) It also doesn't seem as sharp as the other two, but that doesn't bother me as much. I definitely appreciate the decreased file size.

![test](https://github.com/user-attachments/assets/b8a1d3a3-129c-4189-b5d9-b43ded7311da)

**Comment by bp2008** [comment]
I will also nudge it to the left to match your version.

**Comment by aesterling** [comment]
Awesome. When I created my test icon earlier, I had to apply a sharpening filter in Photoshop to get it closer to the native icon, regardless of my high res source file. Maybe it was my scaling interpolation making it soft. At any rate, thanks for all the help. 

Do I understand correctly that I can delete the entire www/ui3/logos folder as it is no longer used?

**Comment by bp2008** [comment]
It can be tricky sometimes with scaling filters.

That is correct.  Likewise the `ui3/launcher-icon.png` file and `ui3/manifest.json` files are no longer used.  And in the next UI3 release, `applet/launcher-icon.png` will no longer be used either.

**Comment by bp2008** [comment]
Here is demo #2.  See what you think of this.  It is a 256x256 graphic this time and I applied the unsharp mask filter in GIMP and positioned it the same as the logo file you made.  11 KB webp.

[UI3-272-pwa-test-2.zip](https://github.com/user-attachments/files/16461678/UI3-272-pwa-test-2.zip)

**Comment by bp2008** [comment]
There is still a bit of "haloing" in this sharpened version but less than in the one you made.

Here's a PNG copy of exactly what the webp file looks like since github won't let me upload webp natively:

![launcher-icon256_ios](https://github.com/user-attachments/assets/f475d04e-5c46-4ee8-bcdf-1050f9bb35e1)

**Comment by aesterling** [comment]
Looks great to my eyes. Latest version is the top left icon in this screenshot.

![newer_icon](https://github.com/user-attachments/assets/32daed57-aa7d-4429-b5e0-74dd9e44cc40)

**Comment by bp2008** [comment]
Thanks.  That will be in the next UI3 release then.

**Comment by aesterling** [comment]
I'm running the latest BI version 5.9.5.3 but when I tap "Add to Home Screen" on iOS it appears to use the old no-padding version of the icon.

I probably have a cluttered mess of old test files in my BI www directory, so I closed BI, moved the www folder to my desktop, and then ran the installer blueirisupdate_64_59503.exe hoping it would install a clean www folder. I was surprised to see no new www folder in C:\Program Files\Blue Iris 5\

What am I missing? Thanks!

**Comment by bp2008** [comment]
I haven't done a UI3 release in a month, so the icon changes aren't being shipped with Blue Iris yet ;)

**Comment by bp2008** [comment]
Also, Blue Iris's patch installers do not include the entire program, only the changed/added files, so I guess it isn't coded to create the www folder if it is missing.

**Comment by aesterling** [comment]
Ahh makes sense. Thanks. I was tricked by the super helpful 🙄 BI release notes that include "UI3 update."

**Comment by bp2008** [comment]
Yeah that message is usually indicative of the changes made in the last several BI updates, not just the last one.
