### ISSUE TITLE
Add "Wildlife" Clips filter

### ISSUE THREAD

**Issue by androdev88** [bp2008/ui3#188]
It was recently added to BI `AI label macros for persons, vehicles, wildlife, myplates`.

Adding
` this.items.push(new DropdownListItem({ id: "wildlife", text: "Wildlife alerts", icon: "#svg_mio_landscape", iconClass: "smallIcon orangeIcon" }));`
works but the icon is missing, it looks like not all material icons are available.

**Comment by bp2008** [comment]
I have to download each material icon and hand-edit its svg markup for compatibility with UI3's icon system, which involves replacing the svg element with a symbol element and I delete unnecessary markup out of it and change the viewport to remove baked-in padding.  It is a whole process.  Then I paste it into ui3's icons.svg file which is where all the SVG icons are loaded from.  All of the available icons are viewable in `ui3/svgtest.htm`.

What icon does Blue Iris use for wildlife?  Can you screenshot it?  I don't use AI so it would be a bit annoying to test myself.

**Comment by androdev88** [comment]
![Screenshot 2024-12-03 212600](https://github.com/user-attachments/assets/9420cfdf-5b0d-4d2f-9610-024bec28fb90)

**Comment by bp2008** [comment]
Thanks.  I see this is probably also being shown as a graphic on the timeline since it appears in the alert list as an icon.  I'm asking BI support for the necessary information to complete this addition.

**Comment by bp2008** [comment]
This should be working in [UI3-278](https://github.com/bp2008/ui3/releases/tag/278).
