### ISSUE TITLE
Event Triggered Icons Error

### ISSUE THREAD

**Issue by indi1984** [bp2008/ui3#189]
![ui3 settings](https://github.com/user-attachments/assets/cd0143a8-713c-4be0-9aba-0bca94f15b5d)

Since 278, when having any of the settings in the photo above enabled (Event Triggered Icons) , I am getting errors in pic below.  I have had "On Motion Trigger" enabled for many versions with no issue up to 277:

![UI3 278 error](https://github.com/user-attachments/assets/d6bfc461-c17b-422c-b744-aedfef676d1a)

**Comment by bp2008** [comment]
Thanks for letting me know.  Fixed in [UI3-279](https://github.com/bp2008/ui3/releases/tag/279).

**Comment by indi1984** [comment]
Thank you sir.
