### ISSUE TITLE
Mobile log in for chrome

### ISSUE THREAD

**Issue by norex94** [bp2008/ui3#19]
Hi, 

I am having an issue on chrome mobile when I am trying to log into UI3. 
I write my user name and password and press log on, the page refreshes and I go back into the login page. This happens also if I mark "auto login". 

I tried this on two mobile phones and the same issue. 

If I go into an incognito mode in chrome, everything works fine as it should be. 

Video of the problem: https://streamable.com/un4xb

Thank you for awesome UI, I use it a lot.

Cheers

**Comment by norex94** [comment]
Also, the BlueIris log says that I never log in when I am experiencing the problem.

**Comment by bp2008** [comment]
This is happening because you have "Data Saver" enabled in Chrome settings, and something about that breaks Blue Iris's login procedure.

**Comment by norex94** [comment]
Thank you, it worked!
