### ISSUE TITLE
Solo camera live view uses main stream for video, but FPS from sub stream

### ISSUE THREAD

**Issue by iankaufmann** [bp2008/ui3#191]
My cameras are set up to have a 15fps main stream and a 5fps sub stream.

When I am viewing "All Cameras" in UI 3, I see the sub streams (as it should), but then when I solo a camera, I see the full resolution main stream.  The trouble is that the FPS is capped at 5fps.

If I go into my camera's settings (Amcrest) and change the sub stream to be 15fps, then I see 15fps in a soloed camera's live view.

So it seems to be locking the FPS to whatever is defined in the sub stream, even though it is showing the feed from the main stream.

Not sure if this is a UI3 or a Blue Iris issue, but I'm running BI v5.9.9.11 and UI3 v277.  

It applies to the live view only.  Clips and timeline are 15fps from the main stream no matter what.

This config:
![Screenshot 2024-12-18 at 12 05 55](https://github.com/user-attachments/assets/6f35dea0-a978-481f-8717-76eabcd40a0d)

Results in this FPS when the camera is soloed, even though the video itself is clearly from the main stream:
![Screenshot 2024-12-18 at 12 06 18](https://github.com/user-attachments/assets/af01a13e-99cd-4368-a557-2d384371a8a5)

While this config:
![Screenshot 2024-12-18 at 12 07 21](https://github.com/user-attachments/assets/16698035-0021-4357-bd39-a61343bdbf6e)

Results in 15 FPS when the camera is soloed:
![Screenshot 2024-12-18 at 12 08 02](https://github.com/user-attachments/assets/f3181aa9-1d04-4915-bcd9-7015affb5241)

**Comment by bp2008** [comment]
That is a Blue Iris thing.  For reasons I do not understand, it uses the sub stream's frame timing for playing the main stream.  I heard it straight from the developer.  It is recommended for FPS and iframe interval to match between main and sub streams.

**Comment by iankaufmann** [comment]
Interesting... well thanks for the quick reply!

I switched the sub streams to 5fps because I'm playing with frigate and it made things work better there.  Guess it's a trade-off.  

I appreciate the clarity, at least I know what the issue is now!
