### ISSUE TITLE
New Update Isssue

### ISSUE THREAD

**Issue by marvinstuart** [bp2008/ui3#2]
Just updated to the latest push with H.264 player now getting pre-loaded in Chrome. 

Issue
When i use chrome on my android phone i get this screen below is does not anything else , U2 works just fine just u3 having this issue in chrome app not desktop
 
https://photos.app.goo.gl/eyflY5C9OOdTzHTG2

Update 
downloaded firefox app and same isssue
https://photos.app.goo.gl/133Pi6CusI992AlC3

If you need a link to the server just tell me

**Comment by bp2008** [comment]
Looks like I broke the loading procedure for all browsers that aren't desktop Chrome.  The previous commit should be fine still.

**Comment by bp2008** [comment]
The latest update has this issue fixed, but I had to replace the old, efficient H.264 decoder with a different one that is only 40% as fast.  https://developer.chrome.com/native-client/migration

**Comment by marvinstuart** [comment]
you are AWESOME it working now . I am really i loving Ui3

**Comment by bp2008** [comment]
You read that wrong.  40% the speed of the original.  As in, it will do 40 FPS on the same hardware that could handle 100 FPS before.
