### ISSUE TITLE
PTZ Movement issue 

### ISSUE THREAD

**Issue by norex94** [bp2008/ui3#20]
Hi

I have issue with PTZ on multiply cameras on the new ui3 version. 

When I move the camera with the arrow keys in the UI3, the UI controls stops responding and the camera constantly moves. No way to stop it. 
If I use blue Iris itself, I have no issue. 
See video for example: https://streamable.com/petyb

I cannot move in one direction. 

It worked fine in previous version.

Thank you and keep up the good work.
cheers

**Comment by bp2008** [comment]
Hmm.  I noticed similar behavior this morning.  Looks like the Android app yields the same results, so it is most likely a new bug in Blue Iris.  I will notify the developer!

**Comment by norex94** [comment]
Okey thank you, I also forgot to mention that I updated BlueIris too.

**Comment by bp2008** [comment]
I've emailed Blue Iris support, providing more details and a link to this issue.  I'd expect a BI update this coming week to resolve the issue.
