### ISSUE TITLE
Frame rate drops after camera reloaded server-side

### ISSUE THREAD

**Issue by macwhiz** [bp2008/ui3#21]
When changes are made to the camera configuration on the Blue Iris server, causing the camera to reload, while the camera is being viewed in the ui3 interface, when ui3 reconnects to the camera the frame rate is very low until you reload ui3 using the browser's reload button. In my case, my camera normally runs around 30 fps; changing the camera config causes ui3 to drop to <5 fps until the ui is reloaded in the browser.

UI3 version 70, Blue Iris 4.8.6.3. Google Chrome 73.0.3683.86 on macOS 10.14.4 (18E226). Also occurs with earlier versions. 

Issue is consistently repeatable.

Steps to reproduce:

1. Open live view of camera in web browser. Streaming quality doesn't seem to matter, but I'm using 1440p. Observe normal FPS in the 30fps range.
2. On Blue Iris server, open the camera's properties.
3. Make some change that will require the camera to reload, such as altering the motion-detection settings.
4. Close the camera properties dialog(s) saving changes, such that the camera view on the Blue Iris console displays color bars momentarily. Observe loss-of-connection message in UI3 session.
5. Wait for UI3 to auto-reconnect.
6. Observe FPS of 1-5 fps.
7. Click browser's Reload button. If necessary, "click anywhere" to enable stream. Observe normal FPS restored.

**Comment by bp2008** [comment]
I've been aware of this for a while.  Unfortunately it is something I have no control over.

I think Blue Iris is locking in the frame rate at the moment it begins producing the video stream.  I'm thinking that because the source stream (the camera) had just been restarted, Blue Iris didn't have an accurate frame rate measurement yet so the frame rate which got locked in was wrong.

**Comment by bp2008** [comment]
I've just emailed the BI developer to see if anything can be done about this.

**Comment by bp2008** [comment]
I've been informed that this will be fixed, but it may not happen before Blue Iris 5 is released.  Therefore it is unlikely that this fix will be backported to Blue Iris 4.

**Comment by bp2008** [comment]
Just updating this issue.  Blue Iris fixed the problem ages ago.
