### ISSUE TITLE
UI3 on Samsung Smart Fridge Browser

### ISSUE THREAD

**Issue by DeFlanko** [bp2008/ui3#23]
Reviewed potentially related issues and they're not the same issue:  #14 

Output from Samsung Smart Fridge browser details:
whatsmybrowser.org/b/KL2KWWV

Seeing as how its a limited browser and on Trizen OS i thought that the Web Interface of BI5 would be the best option.  I was able to login, and see the all cameras dashboard. However when i attempted to view a live stream of a single camera it threw an Error that i was not able to screen grab. If there is web interface log files i can get to post i will but please tell me where those are.

id like to see if development can be made to view and play back cameras for this screen size and orientation. 

Also if there are any other bits of info about the Fridge Browser you need i can get that too as long as it s a web page :)

**Comment by bp2008** [comment]
See if you can get me a screenshot of the error message.  A picture of it taken with your phone is fine.

The main optimization for a tall portrait view in UI3 is to make a new camera group in Blue Iris, include all your cameras in it, and configure its frame size to be a better fit for your display.  https://i.imgur.com/qDoF18x.jpg

If it only has trouble with H.264 streaming modes (such as 720p), then there are a few things you can try.

In UI settings > Video Player section, you can change the H.264 player to JavaScript.  This mode has better compatibility but uses more CPU time, so pick a fairly low-res choice in the streaming quality options.

As a last-resort you should be able to change the streaming quality choice to Jpeg HD, but this has a number of downsides like higher bandwidth usage, poor frame rate, and no audio support.

**Comment by bp2008** [comment]
There are no log files for the web UI and no diagnostic tools I can think of for you to try.

**Comment by DeFlanko** [comment]
![20190614_183608](https://user-images.githubusercontent.com/5233969/59545512-223aca80-8ed4-11e9-9753-f4f895c11d9d.jpg)
![20190614_183559](https://user-images.githubusercontent.com/5233969/59545514-2666e800-8ed4-11e9-91fd-a6e1b4750940.jpg)

**Comment by bp2008** [comment]
That one I would expect to be solved by my earlier recommendations for sure.

**Comment by DeFlanko** [comment]
ok ill give it a go and report back

**Comment by DeFlanko** [comment]
Setting the H.264 to Javascript worked!

Issue closed.

**Comment by bp2008** [comment]
Excellent!
