### ISSUE TITLE
Option to change highlight color 

### ISSUE THREAD

**Issue by brofield** [bp2008/ui3#25]
I have a ui3 monitor running 24/7, and the red highlights for movement used to catch my eye late at night when I'm wanting to see movement on the monitor.

With bi5, the movement highlight color has changed to blue. If this is something that can be changed in ui3, would you please add an option to change it back to red. 

Or alternatively, some other way of making movement highly visible on the monitor.

**Comment by bp2008** [comment]
Hi.

The color is part of the stream sent by Blue Iris, and I have no control over it.  I suggest contacting Blue Iris support about this.

**Comment by brofield** [comment]
Ok. Will try them.
