### ISSUE TITLE
MS detects trojan in loginScripts.js since Sep 30-2019 update

### ISSUE THREAD

**Issue by rrroonn** [bp2008/ui3#26]
![denali](https://user-images.githubusercontent.com/20292325/67532298-158f7400-f709-11e9-8329-4e72bd0a1437.jpg)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:JS/Denali&threatId=-2147223972

The file is included in BlueIris which is why I picked up the problem when updating.

I copied the code in the same file here into an editor and saved to a desktop file and this was immediately detected.  Probably a false-positive but should try to have MS fix this, or adjust code so it no longer matches their signature.

thanks,

Ron

**Comment by bp2008** [comment]
I have no idea where that is coming from.  Nobody else has reported such an issue.

I uploaded my copy of the same file to Virustotal, it came back with the Microsoft engine showing that based on an earlier scan (hash code of the file was a match).  I asked it to rescan the exact same file just now and it came back clean.  So I'm guessing it was a temporary issue with Microsoft's scanning engine.

Is `loginScripts.js` the only file that got flagged?

**Comment by rrroonn** [comment]
Yes, just that one file.

regards,
Ron

**Comment by rrroonn** [comment]
I just updated  Windows Defender virus definitions and tried to copy the file again - still detecting as the same trojan.  I don't think that I would be too unique - just an average Win-10 user - from Australia though - so may be picking up slightly different definitions?  Just a stab in the dark.

Yes, I earlier uploaded the full BI_Installer.exe for a scan which came up clean, which is why I suspect a false positive.

thanks

Ron

**Comment by rrroonn** [comment]
I submitted a sample to MS as a suggested false-positive.  Their automated tools also show the file as clean, so I expect that the problem will go away in a few days.  I will update if/when I hear from them.

**Comment by bp2008** [comment]
I've been installing Windows updates on two machines all evening and re-scanning the thing and still nothing.

I can't try to mitigate this if I can't even reproduce it.  :)

**Comment by rrroonn** [comment]
Yeah, fully understand.  Maybe just leave this open for a week in case something new pops up ... I am sure you have better things to do than installing Windows  ;-)  Thanks for looking at this.

**Comment by rrroonn** [comment]
![submission1](https://user-images.githubusercontent.com/20292325/67624261-b5681180-f871-11e9-9102-d4ace6111ab0.jpg)
I think that this can now be closed.  The file is no longer being detected.

**Comment by bp2008** [comment]
Thanks
