### ISSUE TITLE
Problems when loading ui3 in Homeseer HStouch

### ISSUE THREAD

**Issue by gitbuddy99** [bp2008/ui3#27]
When trying to open ui3 inside HSTouch in an android appliance, all "LOADING" lines show "BUSY" and it doesn't move from there.

Thanks for your help.

Vesrions:
UI3 version 93, Blue Iris version: 5.0.6.2
Homeseer 3.0.0.548
HSTouch Version 3.0.0.51
Mygica s905 running android 5.1.1

![ui3](https://user-images.githubusercontent.com/58091287/69460990-711e4300-0d43-11ea-8b24-8e880c481267.jpg)

**Comment by bp2008** [comment]
Could be something like cookies not being supported in the embedded browser.  Is there a setting for that?  I've never used HSTouch.

You could try going to Blue Iris Settings > Web server > Advanced and put a `^` followed by your android's IP address in the "Limit IP addresses" box.  That will make connections from that IP always receive an administrator session.  If you try this and it works, be sure to check Blue Iris Status > Connections tab to make sure it isn't creating a whole bunch of new sessions when your HSTouch connects.

**Comment by gitbuddy99** [comment]
I haven't found a setting to enable cookies in HSTouch.
Tried logging in with an admin enabled account and got the same result. Can't use the ^ trick because my IP is not static.
Thanks for the suggestion anyways.
