### ISSUE TITLE
Support for Notificationon Alarm

### ISSUE THREAD

**Issue by schorges** [bp2008/ui3#28]
Hello, first thank's for this great work!

is an update planned for a Notification / Toast Extension in Chrom after an alarm?

[https://developers.google.com/web/fundamentals/push-notifications/display-a-notification](url)

**Comment by bp2008** [comment]
Hello. Thank you!

There is nothing planned for notifications through UI3.  This cannot be done entirely by me, as it requires coordinated changes in Blue Iris to support it.  I will ask the Blue Iris developer if he is interested in pursuing this goal.

**Comment by bp2008** [comment]
Alas, there has been no response from Blue Iris Support regarding this.  I imagine not enough people have asked him for such a feature, so it is not a priority at this time.
