### ISSUE TITLE
Dynamic Group for Active Triggers

### ISSUE THREAD

**Issue by Nicknack1234** [bp2008/ui3#29]
Hi,

Great work on the UI! 

I have a enhancement request. A page or group in the UI that dynamically shows the camera streams currently triggered. Your group views do a great job of arranging simultaneous streams on the page but they are statically defined in BI, I would love to see a dynamic group or page like "Active Triggers" that dynamically loads streams from cameras being triggered and then hides them when the trigger ends.

**Comment by bp2008** [comment]
Hello.  Thanks!

UI3 can't implement such a feature on its own (well, it could, but only with severe limitations and _a lot_ of code).  To do it properly, Blue Iris would need to provide an Active Triggers video/audio stream.  You could send an email to Blue Iris support to request this.

**Comment by Nicknack1234** [comment]
Ok no worries I will send it through to BI. Poking around the JSON interface I see the camlist command which lists all cameras, each one has isTriggered True/False. I will have a crack at a simple page, limited to maybe 4 cameras at a time, maybe just pulling jpgs over the http interface to keep it light weight and it might get me by.

**Comment by bp2008** [comment]
Yep.  Pulling H.264 streams to the browser, then decoding and rendering them is absurdly complex at this time, and you've got a limit of 6 concurrent connections to work around, which would mean a limit of 5 streams (leaving one connection available for camlist commands).  So refreshing jpeg snapshots from individual cameras the way to go.  The frame rate and server CPU usage will get worse the more cameras you are trying to stream, but it should at least be usable for any number of cameras.
