### ISSUE TITLE
Feature Request -landscape mode

### ISSUE THREAD

**Issue by marvinstuart** [bp2008/ui3#3]
Feature request 
when viewing an individual camera in landscape mode can you allow the camera feed use up the entire real estate of the phone . and not have the PTZ control, PTZ presets and server status as seen on link below

https://photos.app.goo.gl/IPXiWnVU8a7GKkHo2

**Comment by bp2008** [comment]
Yeah, you won't see it unless you touch near the lower right corner but there is a full screen button there.

**Comment by marvinstuart** [comment]
good to go found it thx
