### ISSUE TITLE
Fast triage flow

### ISSUE THREAD

**Issue by jiriappl** [bp2008/ui3#30]
Hello,

I have made a private change for myself to add a Delete button onto the Alerts page, add support for Del keyboard shortcut and also option to disable Confirmations for deletion in order to allow me to quickly go through alerts and delete them.

Is this something you would be interested in merging to master? If so, I can clean up my change and send a PR. Let me know.

Thanks,
Jiri

**Comment by bp2008** [comment]
Sure!  I may make tweaks before it goes into the next release, but those sound like good additions.

**Comment by jiriappl** [comment]
Opened the PR: https://github.com/bp2008/ui3/pull/31

**Comment by bp2008** [comment]
Thanks!

I fixed a couple minor bugs and included this in release 101.  Expect it in the next Blue Iris patch :)

**Comment by bp2008** [comment]
And if I may say so, your code was much cleaner than expected!!

**Comment by jiriappl** [comment]
Great, thank you for cleaning it up and accepting the patch!
