### ISSUE TITLE
Fails to run on WebOS

### ISSUE THREAD

**Issue by Spuds** [bp2008/ui3#32]
This interface was running using the web browser on a webOS tv (LG).  It seems one of the updates in the last month or two has caused some incompatibility.

I now get an error
```
Uncaught SyntaxError: Unexpected token,
at http://..../ui3/uis.js?v=101-5.0.9.1
[20352:69]
Mozilla/5.0 (Linux: NetCast: U) AppleWebKit/537.31 (KHTML like Gecko) Chrome/38.0.2125.122 Safari/537.31 SmartTV/7.5
```
This is after the login screen, and after the above error the webpage stays on the loading dialog screen you see before the camera views appear.

**Comment by bp2008** [comment]
Thanks for this excellent report.  Expect it to be fixed in the next update!

**Comment by bp2008** [comment]
Fixed in version 102.  You can install it manually or wait for the next Blue Iris update!

**Comment by Spuds** [comment]
Thank you for the quick response and fix
