### ISSUE TITLE
UX Improvement: Export clip flow

### ISSUE THREAD

**Issue by mutasim** [bp2008/ui3#33]
Great work adding in the export via MP4 functionality so quickly - I think this is a game changer!

 I wanted to request an improvement to the flow if poss. Currently it takes minimum 5 clicks/taps to get a file downloaded onto the device. 

My assumption is that the export settings are unlikely to change on a per export basis. Could we look to move that out to the main settings page or similar? Thus saving a step here. 

If the API gives back that exported file, then perhaps we could even skip the list of exported clips screen - if not then having the export list open automatically when complete would also be a welcomed improvement.

Thoughts?

**Comment by bp2008** [comment]
Hi. Thank you for your feedback!

I agree it is not a very well optimized flow.  And I think you are right that most of the time people aren't going to need to change their export configuration.  I have two ideas about this.

1) I could put a checkbox (yes/no toggle) at the bottom of the export configuration dialog named "Always use this configuration".  If enabled, from that point on, the configuration step would be skipped.  I could show a brief toast message at the moment of starting an export, saying "Exporting using saved configuration. To change, see UI Settings > Exports."
2) I could move all of the export-controlling stuff (both the config dialog and the bottom bar) to the side bar instead.  No new toasts.  No new checkboxes or other settings.

![image](https://user-images.githubusercontent.com/5639911/75044726-62991200-547f-11ea-8021-6b788c4a329d.png)

#2 is a lot more work for me but it leaves the configuration more accessible and consolidates more of it into one place.

-------------------

As for actually downloading the exported file, there are a lot of approaches.   I don't want to automatically pop open the full Convert/Export List dialog when exports are finished.  Exporting isn't always fast, and the user might have already started doing something else.  I could open the dialog immediately upon queueing exports, but for slow exports I think a lot of users would just close it and go back later, which actually adds a step.  

The API gives the name of the exported file (immediately upon queueing, before the file is even created).  Once an export job is finished, the file is downloadable via `/clips/name`.

So I can try making the downloads begin automatically the way some web sites start a download after a few seconds of delay, by loading that URL in a hidden i-frame.  Of course, this technique is likely to be suppressed in all manner of undetectable ways by various web browsers, especially after one or two downloads have been done this way, and I don't want people to have to deal with that.  There's also a chance a person might not actually want to download the exported files on the device they used to start the exports, so there's another stupid checkbox to add to the configuration.  This method also requires Blue Iris to add a header to MP4 downloads so the browser doesn't just try to play them in the invisible i-frame.  ... And Blue Iris has a web server setting for disallowing i-frame tags, which might interfere here as well.  So I am leaning away from doing this.

I could put download link(s) directly into the little blue status toast and/or the green success toast.

Or I could scrap both of those toasts and replace them with a tiny status dialog which also includes simple text-based links when they become available.  This is the approach I will probably take.

-------------------

So overall I would be reducing the number of required clicks by 2

**Comment by mutasim** [comment]
What you've proposed sounds a lot more elegant, a straight export/download could be achieved in 3 taps. Great for getting footage off of BI into a suitable messaging app.

**Comment by bp2008** [comment]
The changes have been implemented in version 105, which you can either install manually or get it in the next Blue Iris update.

https://github.com/bp2008/ui3/releases

I think you will be pleased with the results.  I even did the automatic clip downloading, which was perfectly straightforward since I got the BI dev to conditionally include the necessary HTTP header.

**Comment by mutasim** [comment]
Sweet! Just tested it - much slicker :)
