### ISSUE TITLE
Feature request. Quick forward and backward navigation during play

### ISSUE THREAD

**Issue by brofield** [bp2008/ui3#36]
Are you able to implement a method to quickly skip forward and back in the video? Especially with touch control.

Eg scrub forward or back by press and drag. Or the multi click to left or right like on YouTube ( is that patented?)

Just something to make it easier to navigate within the stream, especially on mobile.

**Comment by bp2008** [comment]
You can drag the seek bar of course, but there are also buttons you can enable to skip forward or back some number of seconds.

See UI Settings

### Clips / Alerts section

![image](https://user-images.githubusercontent.com/5639911/78456194-7b403e80-765f-11ea-96cb-b926e9121629.png)

### Hotkeys Section

![image](https://user-images.githubusercontent.com/5639911/78456149-3fa57480-765f-11ea-9b16-7fa7634506f3.png)

**Comment by bp2008** [comment]
The Skip Time option under Hotkeys also affects the buttons you can add to the playback controls bar.
