### ISSUE TITLE
Feature request: newly organised settings page

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#38]
I love the UI except for the settings page.   It's fantastic that there are so many options but its now jsut out of control.  Please add at least a really simple tabbed interface which would be super fast to implement.    

Splitting up the content over windows to hopefully eliminate the scrollbar element within the layout would be very useful.   Right now its just overwhelming and hard to find what you want.

**Comment by bp2008** [comment]
The settings panel already is tabbed, more or less.  Just click on all the section headings to collapse them.

**Comment by arkid** [comment]
But they are all expanded as default.  On top o that there is no Ui element to suggest they expand /collapse and there is also no collapse/expand ALL option.   

So I feel my original comment still stands.   It's very overwhelming when you open the settings and these hidden collapse/expands don't really help at all.

**Comment by bp2008** [comment]
I have vague plans to put a search box at the top of the settings page.  And/or a context-sensitive button to expand or collapse all sections.  I'm thinking if any section is expanded, the button would say "collapse all", and if all are collapsed then it will say "expand all".

A tabbed interface isn't as scalable for mobile devices IMHO.

**Comment by arkid** [comment]
If the issue you are imagining is with the tabs taking up too much horizontal room and therefore the tabs themselves wrap, then one solution could be to make icons for the tabs.  I've done that in an interface a few times for sites I made.     Ie the tabs can have names but at a certain screen width those hide and just clear icons remain.    Currently you have about 10 categories under the settings page but I can imagine that this could be reduced to 6 or 7 with some re-ordering to assist further.

**Comment by bp2008** [comment]
Release 112 resolves this issue as far as I'm going to take it.  :)

It isn't horizontal tabs, but the collapse all button is a quick and easy way to shrink everything down.
