### ISSUE TITLE
Bug: UI3 doesn't seem to understand the BI folder setting 'do NOT monitor free space'

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#39]
It seems that UI3 doesn't understand the "do NOT monitor free space" option that can be checked in the setup of a folder within BI.

If that is checked, if you go to "Disk usage" within UI3 it will display the yellow warning box "Reported disk info is invalid msg...".

It also reports in red "Overallocated" when its not for that drive above the pie graph (which is also displaying incorrect info).

**Comment by bp2008** [comment]
Interesting.

Here is the data UI3 gets in my normal configuration:

![image](https://user-images.githubusercontent.com/5639911/83792757-b6a7bb00-a658-11ea-9e5f-dcc15a6afa55.png)

So to test, I configured the folder on drive "D:" to not monitor free space.

![image](https://user-images.githubusercontent.com/5639911/83792394-3c773680-a658-11ea-86b3-2d971f3334f1.png)

Blue Iris seems to give me bad values for "free" and "total" on the drive that isn't monitoring free space.  I'll ask the developer if there is any meaning in the values given, and if I can rely on "total: 0" to mean free space is not monitored.

**Comment by arkid** [comment]
If it's useful to know what JSON data BI is sending my browser can you confirm how I can obtain that via the dev console ?

**Comment by bp2008** [comment]
Sure.  On the "Network" tab, you'll see a bunch of rows with name `json` -- click on each until you find one where the "Preview" subtab shows `data: {signal...`, then expand the `data` node and the `disks` node.

e.g.

![image](https://user-images.githubusercontent.com/5639911/83795684-0daf8f00-a65d-11ea-88bb-e23aed276325.png)

**Comment by arkid** [comment]
Ok great.... well if useful I can clarify my setup is listed as:

> disks: [{disk: "c:", allocated: 1536000, used: 18285, free: 1876887, total: 1952124},…]
> 0: {disk: "c:", allocated: 1536000, used: 18285, free: 1876887, total: 1952124}
> 1: {disk: "d:", allocated: 1894400, used: 1300303, free: 606466, total: 1907726}
> 2: {disk: "Z:", allocated: 102398976, used: 66, free: 2097152, total: 0}

**Comment by bp2008** [comment]
Does your Z: drive actually have about 100 terabytes allocated, with only 66 megabytes used?

**Comment by bp2008** [comment]
Just trying to figure out if I can trust those data fields.

**Comment by bp2008** [comment]
When I say "Allocated" I mean the value in the Limit size box.  Did you put something close to 100,000  in there?

**Comment by arkid** [comment]
Yes and no ;)   It's a remote network drive with unlimited storage at
google.
This confuses BI which is why they made that setting to not monitor free
space.   And within BI itself that resolves confusions caused by such large
disks.

**Comment by arkid** [comment]
I set limit size to 99999 (GB)

**Comment by bp2008** [comment]
Ok, that makes sense.
So you were able to map an unlimited storage google drive as a network drive in Windows??  Does that perform well?  Or is it just something you handle with a local drive and a sync app?

**Comment by arkid** [comment]
I know there are various ways of doing this, I happen to use a tool called
ExpanDrive that allows you to mount drives from just about any cloud
solution you can imagine.

**Comment by arkid** [comment]
And yes it performs well!   It's perfect for permanent off-site cloud based
cheap storage of old clips.

**Comment by bp2008** [comment]
nice!

**Comment by bp2008** [comment]
The developer got back to me.

> Yes, you are correct in assuming ... total:0 means there is no free space monitoring.  The software internally sets "Free" to 2TB in this case so that recording does not complain about running out of space.  I will suppress that as well to 0 for the JSON output here in today's release.

I've already updated the disk status panel in the source code.  I have several other small improvements planned before I make the next release, so you can expect it in UI3-112 ... whenever that is.

**Comment by arkid** [comment]
Thanks very much! ;)

**Comment by bp2008** [comment]
This issue is resolved in release 112.
