### ISSUE TITLE
Free memory reports as 'undefined' in resources tooltip

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#44]
Just saw this when mouse hovering over the stats in the UI3 interface.  I'm running the latest version of BI.

![Capture](https://user-images.githubusercontent.com/3810108/89828880-b1b72a00-db27-11ea-9891-bff52a5cd8ad.JPG)

**Comment by bp2008** [comment]
Thanks.  Somehow I never noticed that.  Looks like the field this data came from is missing since about the time Blue Iris 5 was released!

I've let the BI developer know.

**Comment by bp2008** [comment]
This will be fixed in the next UI3 update.  Thanks.

**Comment by arkid** [comment]
Great thanks for the prompt response!
