### ISSUE TITLE
Improve video layout user experience

### ISSUE THREAD

**Issue by TonyBrobston** [bp2008/ui3#45]
Hello,

Is there a way to adjust how the video windows are shown in ui3? I dedicate half of a monitor to displaying a 5 cameras, but the video windows are so small that it's difficult to see what is going on in the video. However there is a lot of unused space. Is there any way to take advantage of this unused space?

![image](https://user-images.githubusercontent.com/4724577/91925283-4aaa1280-ec9a-11ea-941b-879b84d9ba9e.png)

I see that the 5 video windows are actually one `video` tag. If they were separate I'd take a stab at some css changes... 🤔 
`<video id="html5MseVideoEle" muted="" draggable="false" unselectable="on" src="blob:http://192.168.1.134:81/34f57589-81a9-4140-8ecd-1f40eb47235f"></video>`

Thanks,
Tony

**Comment by bp2008** [comment]
Hi.  Whenever Blue Iris streams a group of cameras, it composites them together into one video like that.  The good news is, you can change the resolution of the frame it will use, and therefore influence the camera layout.

![Group settings](https://i.imgur.com/qDoF18x.jpg)
