### ISSUE TITLE
Max Bit Rate ignored at playback speed higher than 1x

### ISSUE THREAD

**Issue by pentium90** [bp2008/ui3#48]
1440p profile, limit Bit Rate set to "Yes Limit", Max Bit Rate set to "6144", Playback speed set to 2x = Video Bit Rate in "Stats for nerds" bumps up to >10 Mbps. My VPN connection can do only 10-12 Mbps, so frames are getting dropped, fps goes down to 4-5 fps at higher playback speed.
![Capture](https://user-images.githubusercontent.com/22544731/95647775-4f9c8600-0ad2-11eb-85d4-f6d21b1bdcd0.PNG)

**Comment by bp2008** [comment]
Hi.  Good catch.  I will let Blue Iris support know about the problem!

**Comment by bp2008** [comment]
I've been checking on this every few BI releases and it looks like it is now working correctly in the latest (5.3.3.15).

**Comment by bp2008** [comment]
To clarify, excessive bit rate should no longer be an issue.  Frame rate being reduced and inconsistent, however, can still happen simply because the server isn't able to decode the source video quickly enough.  Fast playback can be pretty demanding on the CPU and disk.
