### ISSUE TITLE
Full screen Design/error ?

### ISSUE THREAD

**Issue by marvinstuart** [bp2008/ui3#5]
Did a quick screen shot on my phone to show you what is happening when a try to go full screen. Not sure if its by design or an error . My thought since i already touched the camera i wanted for full screen  why does it give me another option to pick from my list of cameras to go full 

This doesnt happen when using my desktop pc 

link
https://photos.app.goo.gl/0lrn3P54pWXc51ql2

**Comment by bp2008** [comment]
That is a bug!

The same touch caused the UI to enter full-screen mode and it also acted as a normal click on the video area, which unselected your camera and returned you to the group view.

Thanks for letting me know.  I will fix it.

**Comment by bp2008** [comment]
It is fixed now.

**Comment by marvinstuart** [comment]
thanks as always
