### ISSUE TITLE
Opening alerts sometimes does not open the correct timestamp in the clip

### ISSUE THREAD

**Issue by bp2008** [bp2008/ui3#50]
I haven't got a configuration that allows this issue to be reproduced, but here are the details: https://ipcamtalk.com/threads/blue-iris-ui3.23528/page-143#post-497567

**Comment by bp2008** [comment]
Still unable to reproduce this issue.

**Comment by blkqi** [comment]
I just encountered a similar issue after making the following changes:

- upgraded to Blue Iris 5.3.9.13, and
- relocated the Samba share I use for recording to a new filesystem (same server and export name). Existing files were copied with `rsync -Aavx`.

I have no idea if the changes are related, but now when I press on an alert in UI3 it takes me to the beginning of the clip. If I keep pressing on the alert it will eventually seek to the correct timestamp (usually on the second or third press).

I am recording continuously and logging motion alerts in the database.

**Comment by bp2008** [comment]
Hi @ahaverty.  You'll need to be more specific about what happens, because that URL goes to the timeline, not to a clip or alert as would be appropriate for this issue.  I have tested a few timeline URLs and I do note that sometimes the playback begins at "live" instead of at the requested time.  Is that what you are seeing?  I will need to do more testing to determine if the jump to live is UI3's fault or Blue Iris's.

**Comment by bp2008** [comment]
I have identified and fixed the bug responsible for the `&timeline=####` argument sometimes failing to function properly.  The fix is in release [UI3-234](https://github.com/bp2008/ui3/releases/tag/234).

This issue (#50) remains open however because it is unrelated to the timeline.

**Comment by bp2008** [comment]
Closing this issue. I think it is not relevant anymore.
