### ISSUE TITLE
Common reasons for player interface getting stuck on BUSY?

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#58]
I'm trying to load the interface via local WLAN on a rather old Android Marshmallow (v6) mobile.  This phone has the latest possible google chrome installed but something very odd is happening as all the progress indicators never get past their initial 'BUSY' status.

Are there reasons why an old Android phone may not load UI3 ?

![image](https://user-images.githubusercontent.com/3810108/101992252-a1a78680-3c90-11eb-9dc3-ed6d65724287.png)

**Comment by bp2008** [comment]
Make sure the browser is fully updated.  Also look for the "Data Saver" option in the browser settings and turn it off if you find it.

**Comment by arkid** [comment]
Thanks so much that did the trick!
