### ISSUE TITLE
Allow sidebar to bottom for mobile use.

### ISSUE THREAD

**Issue by rlsmntr** [bp2008/ui3#59]
Please allow the sidebar to be docked at the bottom for mobile use.  This would make the ui3 significantly more friendly for cell phone use.

**Comment by bp2008** [comment]
If only things were that simple!

**Comment by rlsmntr** [comment]
> If only things were that simple!

Would it be possible to have a hide / unhide for it?  Not a web developer so I'm not sure if that would make it easier to do than redeveloping the whole bar for the bottom.  Just looking for some more screen realestate on mobile devices.

**Comment by bp2008** [comment]
> Would it be possible to have a hide / unhide for it? 

You could go to UI Settings > Extra > `Always Show Maximize Button` and enable and use that.  It also hides the top bar along with the side bar.

But generally speaking, UI3 is better in landscape.

**Comment by rlsmntr** [comment]
> > Would it be possible to have a hide / unhide for it?
> 
> You could go to UI Settings > Extra > `Always Show Maximize Button` and enable and use that. It also hides the top bar along with the side bar.
> 
> But generally speaking, UI3 is better in landscape.

Doing that removes the lists so scrolling through to view alerts wouldnt be possible.

**Comment by bp2008** [comment]
Just looking through old issues, I want to point out that UI3 supports a portrait layout since version 188 (Dec 2, 2021).
