### ISSUE TITLE
Where is the idle timeout setting?

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#60]
I'm using a different browser to normal and so the UI3 settings are at their default. I find that after just a few minutes of use that the video stream is timing out.    A msg on screen from UI3 reports that I should change the idle setting in the _UI Settings_ interface. 

However I can't find a single setting that relates to idle / timeout etc.   Can you clarify the name of this setting  ?

**Comment by bp2008** [comment]
Hi.

It is this one:

![image](https://user-images.githubusercontent.com/5639911/103374688-721cba80-4a95-11eb-9442-0d2acbf67819.png)

**Comment by bp2008** [comment]
I'm changing the label of that one to this:

![image](https://user-images.githubusercontent.com/5639911/103374870-de97b980-4a95-11eb-9fb1-b3d4f913e5e4.png)

**Comment by arkid** [comment]
Excellent thanks for clarifying and the update sounds like a great idea!
