### ISSUE TITLE
full screen startup

### ISSUE THREAD

**Issue by xjustbmw** [bp2008/ui3#62]
is there a way to start ui3.html in full screen when loaded?
i have a smart tv loading the interface for a guard person and i would like him to view the cameras in full screen through the browser when loading the page

thanks

**Comment by bp2008** [comment]
It isn't possible to set it to fullscreen automatically unless the browser supports that via a command line option or something (sadly unavailable on a TV operating system), but the maximize=1 URL parameter is hopefully good enough.  https://bp2008.github.io/ui3/ui3/help/help.html#urlparameters
