### ISSUE TITLE
Yo!

### ISSUE THREAD

**Issue by drunkpenguingithub** [bp2008/ui3#7]
Hey dude.  Ive got no audio on UI3.  When I click "get stats for nerds" it shows no streaming audio.   Should it?  Do I have a problem with UI3 or should I talk to Blue Iris support?  I get audio fine locally on the server, just not on the web server.

Thanks!  Im on b23.

**Comment by bp2008** [comment]
Audio should work if:

1) UI3 is using an H.264 streaming method (not jpeg).
2) The current camera or group has an audio stream.
3) Camera Properties > Audio has the Webcast audio box checked.
4) The user account you logged in with has audio permission.

**Comment by drunkpenguingithub** [comment]
Aha!  The users did not have audio access.  Thanks man!  Your the best,
keep up the good work.  UI3 still rocks!
