### ISSUE TITLE
Mouse wheel zoom sometimes seems to work only with the JPEG video streams

### ISSUE THREAD

**Issue by arkid** [bp2008/ui3#75]
This is more just to let you know that this is sometimes happening. 

it is one of those annoying situations where I am unable to recreate it, despite lots of playing around.  

However earlier today in a browser session (current version of Chrome) I found that the mouse wheel didn't zoom at all if I selected any video stream apart from the three jpeg based ones at the bottom of the stream list .   The black box with the zoom value would appear and increase but the video feed didn't actually zoom in at all.

**Comment by bp2008** [comment]
I've been aware of an issue for a couple months now where digital zoom is broken in strange ways in Chromium-derived browsers when using the HTML5 video player.  It only happens on some devices and seems to be very uncommon based on how little I've been hearing about it.  I've only had one other bug report about a video scaling issue which may not even be related.

Anyway, please try zooming in to the max.  If somewhere along the way, the entire browser turns black, it should recover after several seconds and then zooming will work just fine until the next time you close all Chrome processes.  Please try this and let me know what happens.

**Comment by arkid** [comment]
Right now its working for me, irrelevant of what video profile is streaming.  I can't replicate the black screen issue.

**Comment by bp2008** [comment]
Closing obsolete issue.
