### ISSUE TITLE
Feature Request - Redirect requests from phone browsers to mobile apps

### ISSUE THREAD

**Issue by sea3pea0** [bp2008/ui3#77]
I use telegram for receiving notifications about surveillance events on my phone. I include a link to ui3 with the blue iris database record id in my notifications so I have the option to  open up a video stream of the event. It would be awesome if ui3 could detect that I'm doing this from my android phone and automatically redirect my request to the app and play the stream in the app instead of ui3.

**Comment by bp2008** [comment]
Do you know an example URL that would cause the app to be opened?  I doubt the android app implemented such a capability in the first place.

**Comment by sea3pea0** [comment]
As far as I know there isn't  any such functionality built into the app. I tried before to see if I could find any android "intents" built into the app, without any luck. Sorry, I guess this is probably more on the mobile apps rather than ui3.  I guess I'll try to recommend this to Ken.  Thanks
