### ISSUE TITLE
Allow alert previews to be rendered at higher/native resolution

### ISSUE THREAD

**Issue by bp2008** [bp2008/ui3#79]
Deepstack overlays information on the alert image, and it is difficult or impossible to read when scaled down.  There should be an option to have alert hover thumbnails rendered at higher (up to native) resolution according to available screen space.

Alert thumbnails could also be rendered in native resolution within the alert properties panel.

**Comment by bp2008** [comment]
Implemented native resolution previews in [UI3-176](https://github.com/bp2008/ui3/releases/tag/176).  Alert thumbnails in the alert properties panel are not rendered at higher resolution yet.

**Comment by MikeLud** [comment]
Thanks pb2008

Mike

**Comment by bp2008** [comment]
UI3-177 will have [larger thumb capacity in the clip/alert properties panel](https://github.com/bp2008/ui3/commit/5482fad3cb323eac139453f77cef1ad52948815a).
