### ISSUE TITLE
Control-less page for embedding

### ISSUE THREAD

**Issue by sruon** [bp2008/ui3#8]
Hey,

Great work on the UI. 

I am embedding the UI in a Dashboard as an iframe for display on a TV. 

I hacked the HTML to remove all the controls on the left. I would assume that's a common enough use case we could probably add that as a feature. Or maybe I missed something that already exists.

Let me know your thoughts on that one.

Thanks

**Comment by bp2008** [comment]
In the help file it explains you can use the maximize=1 URL parameter to hide all of the UI.  If you want to remove only the left but not the top, then hack away :)

**Comment by sruon** [comment]
My apologies for not reading the readme. I'll close the issue. Thanks !
