### ISSUE TITLE
More switches?

### ISSUE THREAD

**Issue by wilddoktor** [bp2008/ui3#80]
I currently open the ui3 webpage for one of my cameras with the following: /ui3.htm?maximize=1&cam=hd1&tab=live

How do I add switches to the url that will:
1. Set the timeout to 0
2. Set the resolution to JPG

Thanks!

**Comment by bp2008** [comment]
1. There isn't one for that.  See [this](https://bp2008.github.io/ui3/ui3/help/help.html#extensions) if you want to disable the timeout globally.
2. https://bp2008.github.io/ui3/ui3/help/help.html#urlparameters

**Comment by bp2008** [comment]
The help file can only list your streaming profile parameter options if you open it from within UI3.  Anyway `streamingprofile=Jpeg%20HD` should do it.

**Comment by wilddoktor** [comment]
Fantastic, thank you so much!!
