### ISSUE TITLE
Portrait Mode

### ISSUE THREAD

**Issue by jsooter1** [bp2008/ui3#81]
I view UI3 on a portrait monitor. Any chance of getting/adding different aspect ratios? And/Or adding Layouts like the Console?

**Comment by bp2008** [comment]
Hi!

You need to set the resolution of your camera groups in the Blue Iris console.  Try `1080 x 1920` to start with.

![screenshot](https://i.imgur.com/qDoF18x.jpg)

**Comment by bp2008** [comment]
Blue Iris 5.5 and newer supports dynamic group layouts now via UI3, so the default behavior should be much better at utilizing the available screen space.
